### ISSUE TITLE
Merge plan for PR #101: CUDA 12.0 conda support

### ISSUE THREAD

**Issue by bdice** [rapidsai/shared-action-workflows#112]
We're planning to merge PR #101 on Tuesday, July 18. Any repos using workflows that has not yet moved to the branch `cuda-120` will need to make PRs that filter out CUDA 12 jobs from their GitHub Actions workflows like this:

```
matrix_filter: map(select(.CUDA_VER | startswith("11")))
```

See [this cusignal PR](https://github.com/rapidsai/cusignal/pull/583) demonstrating this `matrix_filter`.

Currently [this list of repos](https://github.com/search?q=org%3Arapidsai+%22uses%3A+rapidsai%2Fshared-action-workflows%2F.github%2Fworkflows%2Fpr-builder.yaml%40branch-23.08%22&type=code) is using `branch-23.08`. These need to migrate to use the shared-action-workflows branch `cuda-120` before July 18 **or** introduce matrix filters that skip CUDA 12 builds.

### Tasks
- [ ] cucim https://github.com/rapidsai/cucim/issues/513
- [ ] cugraph
  - [ ] PR to skip: https://github.com/rapidsai/cugraph/pull/3713
  - [ ] Issue for CUDA 12 support: https://github.com/rapidsai/cugraph/issues/3271
- [ ] cugraph-ops
  - [ ] PR to skip: https://github.com/rapidsai/cugraph-ops/pull/523
  - [ ] Issue for CUDA 12 support: https://github.com/rapidsai/cugraph-ops/issues/375
- [x] cuml https://github.com/rapidsai/cuml/issues/5234
- [ ] cuopt
  - [ ] PR to skip: https://github.com/rapidsai/cuopt/pull/1259
  - [ ] Issue for CUDA 12 support: https://github.com/rapidsai/cuopt/issues/992
- [x] cusignal https://github.com/rapidsai/cusignal/pull/583
- [x] integration
  - [x] PR enabling CUDA 12 support: https://github.com/rapidsai/integration/pull/662
    - (metapackage is currently broken due to missing cugraph)
  - [ ] Issue for CUDA 12 support: https://github.com/rapidsai/ops/issues/2533
- [x] rapids-cmake https://github.com/rapidsai/rapids-cmake/pull/437
- [x] xgboost-conda (marking complete because this repo will be archived) https://github.com/rapidsai/xgboost-feedstock/issues/4

(Note that xgboost and other packages aren't using the same shared-action-workflows.)

**Comment by jakirkham** [comment]
Let's drop [`xgboost-conda`]( https://github.com/rapidsai/xgboost-conda ) as that repo is going away. It is being replaced with [`rapidsai/xgboost-feedstock`]( https://github.com/rapidsai/xgboost-feedstock )

Do we still need [the `integration` repo]( https://github.com/rapidsai/integration )?

Am ok either skipping cuCIM or handling it with the others here. We are pretty much down to the CUDA 12 PR there and it is getting close

**Comment by bdice** [comment]
I don't think we can make a decision to "drop" any repos unless broken CI after merging PR #101 is a viable outcome for those repos.

**Comment by jakirkham** [comment]
Not following

The `xgboost-conda` repo is being archived. Let's not spend time on that

The cuCIM repo is down to the CUDA 12 PR that is nearly done. Not sure it is worth changing the GHA branch to only change it back again

Idk the state of the `integration` repo. Maybe @raydouglass can chime in

**Comment by bdice** [comment]
We still rely on `integration` for the `rapids` metapackage, which is our primary conda installation entrypoint. See https://github.com/rapidsai/integration/pull/662
